version: "3.9"

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  webapp:
    restart: always
    build:
      context: .
    volumes:
      - .:/test_message/test_message
    ports:
      - "8000:8000"
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  flower:
    restart: always
    build:
      context: .
    volumes:
      - .:/test_message/test_message
    ports:
      - "5555:5555"
    command: ['celery', '-A', 'test_message', 'flower']

