# Generated by Django 4.1.1 on 2022-09-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='operator_code',
            field=models.CharField(default='000', max_length=3),
        ),
    ]
