# Generated by Django 4.1.1 on 2022-09-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapi', '0002_client_operator_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='operator_code',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
