# Generated by Django 4.1.1 on 2022-09-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapi', '0003_alter_client_operator_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='operator_code',
            field=models.CharField(blank=True, default='dja', max_length=3),
        ),
    ]
