# Generated by Django 4.1.1 on 2022-09-26 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messageapi', '0004_alter_client_operator_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='operator_code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='message',
            name='mail_list_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='messageapi.maillist'),
        ),
    ]
